### PR TITLE
Small edits

### PR DESCRIPTION
**Pull request by smcgregor**
I made small edits throughout the document.

In general you need to introduce what something does before explaining why that is the case. In several places it would be good if you give a 2 sentence summary before jumping into the details.

You might need to generate a diagram for Resource and ResourceItem because it is difficult to read the list of use cases and know how and why these all fit together. I am less immediately concerned by what actions performed, and more concerned by how everything fits together. You could also structure the "Features" section of `Resource, ResourceItem` better.

### CODE REVIEW

**Comment by SummerWish** [comment]
Thank you for your advice! Adding more explaination

**Comment by SummerWish** [comment]
Hi, I added more explainations and images for the documentation, please have a check :-)

**Comment by smcgregor** [comment]
Excellent! Can you please open a pull request to [privly-organization](https://github.com/privly/privly-organization)? You can open a new "docs" folder. Once that is merged we will add a link to it in the source code and on priv.ly/develop.

**Comment by SummerWish** [comment]
Done :-) https://github.com/privly/privly-organization/pull/39

**Pull request merged**
